# Generated by Django 4.2.7 on 2025-12-29 18:41

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_rank', models.CharField(choices=[('none', 'No Rank'), ('connector', 'Connector'), ('builder', 'Builder'), ('professional', 'Professional'), ('executive', 'Executive'), ('director', 'Director'), ('crown', 'Crown')], default='none', max_length=20)),
                ('main_leg_volume', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Volume of the largest leg', max_digits=12)),
                ('other_legs_volume', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Combined volume of all other legs', max_digits=12)),
                ('weekly_bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Weekly bonus for current rank', max_digits=8)),
                ('weeks_remaining', models.IntegerField(default=0, help_text='Weeks remaining for bonus payment (max 52)')),
                ('last_rank_check', models.DateTimeField(auto_now=True)),
                ('rank_achieved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rank', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rank',
                'verbose_name_plural': 'Ranks',
            },
        ),
    ]
