# Generated by Django 4.2.7 on 2025-12-29 18:41

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Main wallet balance for deposits and withdrawals', max_digits=12)),
                ('registration_bonus', models.DecimalField(decimal_places=2, default=10.0, help_text='Registration bonus (max $10, can only use 10% for subscription)', max_digits=5)),
                ('referral_code', models.CharField(blank=True, help_text='Unique referral code for sharing', max_length=10, unique=True)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, help_text='Total earnings from all sources (for 3x cap calculation)', max_digits=12)),
                ('total_invested', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount invested in subscriptions', max_digits=12)),
                ('direct_referrals_count', models.IntegerField(default=0, help_text='Number of direct referrals (Level 1)')),
                ('is_active_investor', models.BooleanField(default=False, help_text='True if user has at least one active subscription')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when user registered')),
                ('trc20_wallet_address', models.CharField(blank=True, help_text="User's TRC20 USDT wallet address for withdrawals", max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('referred_by', models.ForeignKey(blank=True, help_text='User who referred this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-joined_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
