# Generated by Django 4.2.7 on 2025-12-29 18:41

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('purchase', 'Package Purchase'), ('commission', 'Referral Commission'), ('bonus', 'Registration Bonus'), ('daily_income', 'Daily Bond Income'), ('weekly_bonus', 'Weekly Rank Bonus')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('txn_hash', models.CharField(blank=True, help_text='TRC20 transaction hash', max_length=100, null=True)),
                ('wallet_address', models.CharField(blank=True, help_text='TRC20 wallet address', max_length=50, null=True)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Transaction fee (5% for withdrawals)', max_digits=8)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Amount after fees', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional details about the transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='investment.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepositAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Unique TRC20 address for deposits', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deposit Address',
                'verbose_name_plural': 'Deposit Addresses',
            },
        ),
    ]
