# Generated by Django 4.2.7 on 2026-02-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositaddress',
            name='last_checked',
            field=models.DateTimeField(blank=True, help_text='Last time this address was checked for deposits', null=True),
        ),
        migrations.AddField(
            model_name='depositaddress',
            name='private_key_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted private key for this address'),
        ),
    ]
