# Generated by Django 4.2.7 on 2025-12-29 18:41

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Investment amount', max_digits=10)),
                ('tier', models.CharField(choices=[('tier_1', 'Tier 1 ($50-$3,000 @ 6%)'), ('tier_2', 'Tier 2 ($3,001-$5,000 @ 8%)'), ('tier_3', 'Tier 3 ($5,001+ @ 10%)')], help_text='Auto-calculated based on amount', max_length=10)),
                ('monthly_rate', models.DecimalField(decimal_places=2, help_text='Monthly return rate (e.g., 6.00 for 6%)', max_digits=4)),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount earned from this subscription', max_digits=10)),
                ('earnings_cap', models.DecimalField(decimal_places=2, help_text='Maximum earnings (3x the amount)', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Active subscriptions earn daily bond income')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When subscription was purchased')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When subscription reached 3x cap', null=True)),
                ('bonus_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount of registration bonus used for this purchase', max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-started_at'],
            },
        ),
    ]
