# Generated by Django 4.2.7 on 2025-12-29 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(help_text='Level in MLM structure (1-20 for generation income, 0 for daily bond)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_type', models.CharField(choices=[('generation', 'Generation Income'), ('daily_bond', 'Daily Bond Income')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional details about the commission')),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(help_text='User whose activity generated this commission', on_delete=django.db.models.deletion.CASCADE, related_name='commissions_generated', to=settings.AUTH_USER_MODEL)),
                ('source_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='investment.subscription')),
                ('user', models.ForeignKey(help_text='User receiving the commission', on_delete=django.db.models.deletion.CASCADE, related_name='commissions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
                'ordering': ['-paid_at'],
                'indexes': [models.Index(fields=['user', '-paid_at'], name='earnings_co_user_id_4f103c_idx'), models.Index(fields=['from_user', '-paid_at'], name='earnings_co_from_us_2036db_idx')],
            },
        ),
    ]
